# About Block
aboutTitle: "LETTER FROM THE SECRETARY GENERAL"
letterContent: "Dear Delegates,\n

As the Secretary General of IIT Guwahati Model United Nations Conference (IITGMUN) 2018, I could not be more venerated to welcome you all on behalf of my passionate team to the most ambitious version of the IIT Guwahati Model United Nations Conference - Alcheringa yet.

Every year, IITGMUN endeavors to provide a simulated learning platform to like-minded folks with a zealous passion for debating, international diplomacy as well as politics, and deliberative problem-solving. As a learning conference, we prioritize the development of mindset for finding the solutions to pressing world issues by putting oneself in the shoes of a country's representative. We believe that the best way to learn about international diplomacy is by actually doing it. At its core, the IITGMUN Conference is planned, organized, and directed in its totality by a passionate team of IIT Guwahati students that hail from different academic and cultural backgrounds, bringing their unique experiences to the dais. Over the years, we have been successful in delivering thought-intensive conferences to novice as well as seasoned delegates.  

The contemporary world scenario has been dominated by disruptions, both positive and negative. While the former can serve as a driving force for the global growth engine, dealing with the latter requires meticulous planning and deliberation. As a proponent of this thought, we have handpicked three agendae for this winter and set the floor for discussion on the same.

Namely:
UNGA: Preparing for Trans-Arctic Seafaring: Resolving the Impasse over the North-West Passage

ECOSOC: Fulfilling UN Sustainable Development Goals in the Age of Artificial Intelligence

Lok Sabha : Elucidation of Privacy and its Consequences as a Right

All these agendae are the product of incessant discussions and brainstorming among the team members to deliver the most debatable and relevant global quandaries to the participants. The selectivity of these agendae itself reflects our commitment to deliver the best we possibly can and traverse beyond the conventional line of thought.
  
We as a generation have the best time and resources, enumerated with the experience of older generations, to shape the world in a way we want. The onus is on us to act and deliberate as the choices of today will be governing the future in an unprecedented manner.

With an abyssal optimism, I leave you with the mantle and ask you to take part in an event that awaits a brilliant ensemble of delegates who dare to take on upcoming challenges in the world with courage and diplomacy. Wishing you all the very best of luck for the conference.

Sincerely,
Paridhi Kothari
Secretary General
IIT Guwahati Model UN Conference
"